 - name: Create a login user for your VPS
   tags: system
   with_dict: "{{ system_user }}"
   user:
    name: "{{ system_user.project.user_login }}"
    password: "{{ system_user.project.user_password }}"
    groups: # Empty by default, here we give it some groups
     - sudo
     - www-data
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    system: no             # Defaults to no
    createhome: yes        # Defaults to yes
    home: /home/{{ system_user.project.user_login }}  # Defaults to /home/<username>